apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: pool-frontend:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
              ephemeral-storage: 64Mi
            limits:
              memory: 128Mi
              ephemeral-storage: 128Mi